In [1]:
import numpy as np

### Задание 1.1

In [6]:
a = np.array([i for i in range(12, 24)])
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [19]:
b1 = a.reshape(6, 2)
b2 = a.reshape(2, 6)
b3 = a.reshape(3, 4)
b4 = a.reshape(4, 3)
b5 = a.reshape(12, 1)

print(b1)
print()
print(b2)
print()
print(b3)
print()
print(b4)
print()
print(b5)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [28]:
c1 = a.reshape(6, -1)
c2 = a.reshape(4, -1)
c3 = a.reshape(3, -1)
c4 = a.reshape(-1, 4)
c5 = a.reshape(-1, 3)

print(c1)
print()
print(c2)
print()
print(c3)
print()
print(c4)
print()
print(c5)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [29]:
print(np.shape(a))
print(np.shape(b5))

(12,)
(12, 1)


In [39]:
b5[11]

array([23])

Обращение к элементам массива размером (12, 1) через библиотеку numpy происходит по единственному индексу. Ответ: да, массив можно назвать одномерным

### Задание 1.2

In [42]:
task2 = np.random.randn(3, 4)
task2

array([[ 0.79713796, -0.32477197, -1.26900119, -0.82887129],
       [ 0.51127966, -1.41067008,  1.06551959,  1.16589396],
       [ 1.77453315,  0.9653977 , -0.56525783,  0.02989912]])

In [44]:
task2_1 = task2.flatten()
task2_1

array([ 0.79713796, -0.32477197, -1.26900119, -0.82887129,  0.51127966,
       -1.41067008,  1.06551959,  1.16589396,  1.77453315,  0.9653977 ,
       -0.56525783,  0.02989912])

In [46]:
print(task2.size)
print(task2_1.size)

12
12


### Задание 1.3

In [47]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [49]:
b = np.arange(20, 1, -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [53]:
if a.all == b.all:
    print("True")
else:
    print("False")

False


????? Здесь не разобрался ?????

### Задание 1.4

In [72]:
a = np.zeros((3, 2))
b = np.ones((4, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [73]:
np.vstack((a, b))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

### Задание 1.5

In [77]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [81]:
A = a.reshape(3, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
At = A.T
At

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [100]:
B = np.dot(At, A)
B

array([[ 80,  92, 104, 116],
       [ 92, 107, 122, 137],
       [104, 122, 140, 158],
       [116, 137, 158, 179]])

In [101]:
B.shape

(4, 4)

In [102]:
np.linalg.det(B)

0.0

Матрица B является вырожденной, у таких матриц не существует обратной матрицы

### Задание 1.6

In [92]:
genreator = np.random.seed(42)

In [124]:
c = np.array([np.random.randint(16) for _ in range(16)])
c

array([ 1,  3,  8, 11, 13,  1,  9,  8,  9,  4,  1,  3, 11, 14, 11,  6])

In [125]:
C = c.reshape(4, 4)
C

array([[ 1,  3,  8, 11],
       [13,  1,  9,  8],
       [ 9,  4,  1,  3],
       [11, 14, 11,  6]])

In [126]:
D = B + C * 10
D

array([[ 90, 122, 184, 226],
       [222, 117, 212, 217],
       [194, 162, 150, 188],
       [226, 277, 268, 239]])

In [127]:
print(np.linalg.det(D))
print(np.linalg.matrix_rank(D))

-227856999.9999998
4


In [128]:
D_inv = np.linalg.inv(D)
D_inv

array([[-0.00674256,  0.00485585,  0.00519554, -0.00211993],
       [-0.00053858, -0.00907227,  0.00528893,  0.00458612],
       [-0.00130406,  0.00963385, -0.0199189 ,  0.0081545 ],
       [ 0.00846233, -0.00487981,  0.01129305, -0.00827054]])

### Задание 1.7

In [129]:
D_inv = D_inv.flatten()

for i in range(0, len(D_inv)):
    D_inv[i] = 1 if D_inv[i] > 0 else 0

D_inv = D_inv.reshape(4, 4)
D_inv

array([[0., 1., 1., 0.],
       [0., 0., 1., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [130]:
E = np.where(D_inv, B, C)
E

array([[  1,  92, 104,  11],
       [ 13,   1, 122, 137],
       [  9, 122,   1, 158],
       [116,  14, 158,   6]])

### Задание 2

In [131]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])
a = a.T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [136]:
mean_a = [np.mean(a[:, 0]), np.mean(a[:, 1])]
mean_a

[2.0, 8.4]

### Задание 3

In [138]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 4

In [143]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
print(a_centered_sp)
b = a_centered_sp / (len(a_centered) - 1)
print(b)


8.0
2.0


In [145]:
cov_a = np.cov(a.T)
cov_a

array([[1. , 2. ],
       [2. , 4.3]])